version: "3.9"
services:
  haptor:
    image: haptor:latest
    build:
      context: ./build
      dockerfile: Dockerfile
    entrypoint: ["/entrypoint.sh"]
    environment:
      - LISTENERS=${LISTENERS-10}
      - BALANCING_ALGORITHM=${BALANCING_ALGORITHM-roundrobin}
    ports:
      - target: 8080
        published: ${LISTEN_PORT-8050}
        protocol: tcp
        mode: host
    container_name: haptor

